# Database Configuration ##
spring.datasource.url=jdbc:mysql://localhost:3306/roomies_db_test?serverTimezone=Europe/Athens

##set time zone
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Athens
spring.jackson.time-zone=Europe/Athens

spring.config.import=optional:file:.env[.properties]

spring.datasource.username=${DB_USERNAME_ROOMIES_TEST}
spring.datasource.password=${DB_PASSWORD_ROOMIES_TEST}
spring.jpa.hibernate.ddl-auto=create-drop

## UNCOMMENT AT FIRST UPDATE, COMMENT AT CREATE
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:sql/regions.sql, classpath:sql/educational_units.sql
spring.sql.init.encoding=UTF-8
spring.sql.init.platform=mysql



## File upload
#spring.servlet.multipart.max-file-size=5MB
#spring.servlet.multipart.max-request-size=10MB


# Logging (debugging)
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG